// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: distconf/v1/distconf.proto

package distconfv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchEvent_Kind int32

const (
	WatchEvent_KIND_UNSPECIFIED WatchEvent_Kind = 0
	WatchEvent_PUT              WatchEvent_Kind = 1
	WatchEvent_DELETE           WatchEvent_Kind = 2
	WatchEvent_EXPIRED          WatchEvent_Kind = 3
)

// Enum value maps for WatchEvent_Kind.
var (
	WatchEvent_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "PUT",
		2: "DELETE",
		3: "EXPIRED",
	}
	WatchEvent_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"PUT":              1,
		"DELETE":           2,
		"EXPIRED":          3,
	}
)

func (x WatchEvent_Kind) Enum() *WatchEvent_Kind {
	p := new(WatchEvent_Kind)
	*p = x
	return p
}

func (x WatchEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_distconf_v1_distconf_proto_enumTypes[0].Descriptor()
}

func (WatchEvent_Kind) Type() protoreflect.EnumType {
	return &file_distconf_v1_distconf_proto_enumTypes[0]
}

func (x WatchEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEvent_Kind.Descriptor instead.
func (WatchEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{8, 0}
}

type KeyValue struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key       string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// key 级单调版本：每次 Put/Delete(产生墓碑) +1
	Version int64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// 全局修订号（= 该变更对应的 Raft 日志 index），全序
	Revision int64 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	// 租约时长（毫秒），0 表示永不过期
	TtlMs int64 `protobuf:"varint,6,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	// 绝对过期时间（Unix 毫秒），由 leader 在写日志时盖戳
	ExpireAtMs    int64 `protobuf:"varint,7,opt,name=expire_at_ms,json=expireAtMs,proto3" json:"expire_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KeyValue) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *KeyValue) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *KeyValue) GetExpireAtMs() int64 {
	if x != nil {
		return x.ExpireAtMs
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Found bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Kv    *KeyValue              `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`
	// 响应生成时本节点已应用到的全局 revision（客户端可据此判断读的新鲜度）
	AppliedRevision int64 `protobuf:"varint,3,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	LeaderId        int32 `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *GetResponse) GetAppliedRevision() int64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *GetResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type PutRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key       string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	TtlMs     int64                  `protobuf:"varint,4,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	// CAS：
	//
	//	expected_version = -1 不检查；
	//	expected_version = 0  要求 key 不存在；
	//	expected_version > 0  要求当前 version 恰好相等。
	ExpectedVersion int64 `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{3}
}

func (x *PutRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *PutRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            *KeyValue              `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{4}
}

func (x *PutResponse) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *PutResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type DeleteRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key       string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// 可选 CAS；-1 表示无条件
	ExpectedVersion int64 `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	LeaderId      int32                  `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *DeleteResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DeleteResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type WatchRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// key 为空 => 订阅整个 namespace
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// 客户端上次收到的最大 revision；服务端从 from_revision+1 开始补发
	FromRevision  int64 `protobuf:"varint,3,opt,name=from_revision,json=fromRevision,proto3" json:"from_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{7}
}

func (x *WatchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WatchRequest) GetFromRevision() int64 {
	if x != nil {
		return x.FromRevision
	}
	return 0
}

type WatchEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Kind     WatchEvent_Kind        `protobuf:"varint,1,opt,name=kind,proto3,enum=distconf.v1.WatchEvent_Kind" json:"kind,omitempty"`
	Kv       *KeyValue              `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`
	Revision int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	// 事件产生后集群已应用到的 revision
	ClusterRevision int64 `protobuf:"varint,4,opt,name=cluster_revision,json=clusterRevision,proto3" json:"cluster_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{8}
}

func (x *WatchEvent) GetKind() WatchEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return WatchEvent_KIND_UNSPECIFIED
}

func (x *WatchEvent) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *WatchEvent) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *WatchEvent) GetClusterRevision() int64 {
	if x != nil {
		return x.ClusterRevision
	}
	return 0
}

type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LeaseTtlMs    int64                  `protobuf:"varint,6,opt,name=lease_ttl_ms,json=leaseTtlMs,proto3" json:"lease_ttl_ms,omitempty"`
	ExpireAtMs    int64                  `protobuf:"varint,7,opt,name=expire_at_ms,json=expireAtMs,proto3" json:"expire_at_ms,omitempty"`
	Revision      int64                  `protobuf:"varint,8,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{9}
}

func (x *Instance) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Instance) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Instance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Instance) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Instance) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Instance) GetLeaseTtlMs() int64 {
	if x != nil {
		return x.LeaseTtlMs
	}
	return 0
}

func (x *Instance) GetExpireAtMs() int64 {
	if x != nil {
		return x.ExpireAtMs
	}
	return 0
}

func (x *Instance) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LeaseTtlMs    int64                  `protobuf:"varint,6,opt,name=lease_ttl_ms,json=leaseTtlMs,proto3" json:"lease_ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RegisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterRequest) GetLeaseTtlMs() int64 {
	if x != nil {
		return x.LeaseTtlMs
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *RegisterResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HeartbeatRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *HeartbeatResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type DiscoverRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service   string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// 是否持续推送（true => 流保持打开，实例集合变化时推送增量）
	Watch         bool `protobuf:"varint,3,opt,name=watch,proto3" json:"watch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{14}
}

func (x *DiscoverRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DiscoverRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DiscoverRequest) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

type DiscoverResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Instances []*Instance            `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	// watch=true 时使用：是否为快照(false 快照/true 增量)
	Incremental     bool        `protobuf:"varint,2,opt,name=incremental,proto3" json:"incremental,omitempty"`
	Added           []*Instance `protobuf:"bytes,3,rep,name=added,proto3" json:"added,omitempty"`
	Removed         []*Instance `protobuf:"bytes,4,rep,name=removed,proto3" json:"removed,omitempty"`
	AppliedRevision int64       `protobuf:"varint,5,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{15}
}

func (x *DiscoverResponse) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *DiscoverResponse) GetIncremental() bool {
	if x != nil {
		return x.Incremental
	}
	return false
}

func (x *DiscoverResponse) GetAdded() []*Instance {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *DiscoverResponse) GetRemoved() []*Instance {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *DiscoverResponse) GetAppliedRevision() int64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{16}
}

type InfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IsLeader          bool                   `protobuf:"varint,2,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	LeaderId          int32                  `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CommittedRevision int64                  `protobuf:"varint,4,opt,name=committed_revision,json=committedRevision,proto3" json:"committed_revision,omitempty"`
	AppliedRevision   int64                  `protobuf:"varint,5,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	Nodes             []*Node                `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{17}
}

func (x *InfoResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *InfoResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *InfoResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *InfoResponse) GetCommittedRevision() int64 {
	if x != nil {
		return x.CommittedRevision
	}
	return 0
}

func (x *InfoResponse) GetAppliedRevision() int64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *InfoResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{18}
}

func (x *Node) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term  int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"` // 本实现为单静态 leader，term 恒为 1
	// Types that are valid to be assigned to Op:
	//
	//	*LogEntry_Put
	//	*LogEntry_Delete
	//	*LogEntry_Register
	//	*LogEntry_Heartbeat
	//	*LogEntry_ExpireKeys
	//	*LogEntry_ExpireServices
	Op            isLogEntry_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{19}
}

func (x *LogEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetOp() isLogEntry_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *LogEntry) GetPut() *PutOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *LogEntry) GetDelete() *DeleteOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *LogEntry) GetRegister() *RegisterOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *LogEntry) GetHeartbeat() *HeartbeatOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *LogEntry) GetExpireKeys() *ExpireKeysOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_ExpireKeys); ok {
			return x.ExpireKeys
		}
	}
	return nil
}

func (x *LogEntry) GetExpireServices() *ExpireServicesOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_ExpireServices); ok {
			return x.ExpireServices
		}
	}
	return nil
}

type isLogEntry_Op interface {
	isLogEntry_Op()
}

type LogEntry_Put struct {
	Put *PutOp `protobuf:"bytes,3,opt,name=put,proto3,oneof"`
}

type LogEntry_Delete struct {
	Delete *DeleteOp `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

type LogEntry_Register struct {
	Register *RegisterOp `protobuf:"bytes,5,opt,name=register,proto3,oneof"`
}

type LogEntry_Heartbeat struct {
	Heartbeat *HeartbeatOp `protobuf:"bytes,6,opt,name=heartbeat,proto3,oneof"`
}

type LogEntry_ExpireKeys struct {
	ExpireKeys *ExpireKeysOp `protobuf:"bytes,7,opt,name=expire_keys,json=expireKeys,proto3,oneof"`
}

type LogEntry_ExpireServices struct {
	ExpireServices *ExpireServicesOp `protobuf:"bytes,8,opt,name=expire_services,json=expireServices,proto3,oneof"`
}

func (*LogEntry_Put) isLogEntry_Op() {}

func (*LogEntry_Delete) isLogEntry_Op() {}

func (*LogEntry_Register) isLogEntry_Op() {}

func (*LogEntry_Heartbeat) isLogEntry_Op() {}

func (*LogEntry_ExpireKeys) isLogEntry_Op() {}

func (*LogEntry_ExpireServices) isLogEntry_Op() {}

type PutOp struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Namespace  string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key        string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value      []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	TtlMs      int64                  `protobuf:"varint,4,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	ExpireAtMs int64                  `protobuf:"varint,5,opt,name=expire_at_ms,json=expireAtMs,proto3" json:"expire_at_ms,omitempty"`
	// CAS 在 apply（状态机）阶段判定，保证“判定顺序 == 日志顺序”。
	ExpectedVersion int64 `protobuf:"varint,6,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PutOp) Reset() {
	*x = PutOp{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutOp) ProtoMessage() {}

func (x *PutOp) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutOp.ProtoReflect.Descriptor instead.
func (*PutOp) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{20}
}

func (x *PutOp) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutOp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutOp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutOp) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *PutOp) GetExpireAtMs() int64 {
	if x != nil {
		return x.ExpireAtMs
	}
	return 0
}

func (x *PutOp) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type DeleteOp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteOp) Reset() {
	*x = DeleteOp{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOp) ProtoMessage() {}

func (x *DeleteOp) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOp.ProtoReflect.Descriptor instead.
func (*DeleteOp) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteOp) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteOp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteOp) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type RegisterOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LeaseTtlMs    int64                  `protobuf:"varint,6,opt,name=lease_ttl_ms,json=leaseTtlMs,proto3" json:"lease_ttl_ms,omitempty"`
	ExpireAtMs    int64                  `protobuf:"varint,7,opt,name=expire_at_ms,json=expireAtMs,proto3" json:"expire_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOp) Reset() {
	*x = RegisterOp{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOp) ProtoMessage() {}

func (x *RegisterOp) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOp.ProtoReflect.Descriptor instead.
func (*RegisterOp) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{22}
}

func (x *RegisterOp) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterOp) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RegisterOp) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterOp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterOp) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterOp) GetLeaseTtlMs() int64 {
	if x != nil {
		return x.LeaseTtlMs
	}
	return 0
}

func (x *RegisterOp) GetExpireAtMs() int64 {
	if x != nil {
		return x.ExpireAtMs
	}
	return 0
}

type HeartbeatOp struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Namespace  string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service    string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	InstanceId string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// 续租守卫：仅当实例当前 revision 相等才续租
	// （实例恰好在提议后被到期日志摘除时返回 not found）。
	GuardRevision int64 `protobuf:"varint,8,opt,name=guard_revision,json=guardRevision,proto3" json:"guard_revision,omitempty"`
	// leader 盖戳的新绝对过期时间（TTL 沿用注册时的值）。
	NewExpireAtMs int64 `protobuf:"varint,9,opt,name=new_expire_at_ms,json=newExpireAtMs,proto3" json:"new_expire_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatOp) Reset() {
	*x = HeartbeatOp{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatOp) ProtoMessage() {}

func (x *HeartbeatOp) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatOp.ProtoReflect.Descriptor instead.
func (*HeartbeatOp) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{23}
}

func (x *HeartbeatOp) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HeartbeatOp) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HeartbeatOp) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeartbeatOp) GetGuardRevision() int64 {
	if x != nil {
		return x.GuardRevision
	}
	return 0
}

func (x *HeartbeatOp) GetNewExpireAtMs() int64 {
	if x != nil {
		return x.NewExpireAtMs
	}
	return 0
}

type ExpireKeysOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ExpireKey           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireKeysOp) Reset() {
	*x = ExpireKeysOp{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireKeysOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireKeysOp) ProtoMessage() {}

func (x *ExpireKeysOp) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireKeysOp.ProtoReflect.Descriptor instead.
func (*ExpireKeysOp) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{24}
}

func (x *ExpireKeysOp) GetItems() []*ExpireKey {
	if x != nil {
		return x.Items
	}
	return nil
}

type ExpireKey struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key       string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// 删除守卫：只有当前值的 revision == guard_revision 才删，
	// 防止“扫描到期 -> 日志提交”之间 key 被重新 Put 而误删。
	GuardRevision int64 `protobuf:"varint,3,opt,name=guard_revision,json=guardRevision,proto3" json:"guard_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireKey) Reset() {
	*x = ExpireKey{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireKey) ProtoMessage() {}

func (x *ExpireKey) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireKey.ProtoReflect.Descriptor instead.
func (*ExpireKey) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{25}
}

func (x *ExpireKey) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExpireKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExpireKey) GetGuardRevision() int64 {
	if x != nil {
		return x.GuardRevision
	}
	return 0
}

type ExpireServicesOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ExpireService       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireServicesOp) Reset() {
	*x = ExpireServicesOp{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireServicesOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireServicesOp) ProtoMessage() {}

func (x *ExpireServicesOp) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireServicesOp.ProtoReflect.Descriptor instead.
func (*ExpireServicesOp) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{26}
}

func (x *ExpireServicesOp) GetItems() []*ExpireService {
	if x != nil {
		return x.Items
	}
	return nil
}

type ExpireService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	GuardRevision int64                  `protobuf:"varint,4,opt,name=guard_revision,json=guardRevision,proto3" json:"guard_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireService) Reset() {
	*x = ExpireService{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireService) ProtoMessage() {}

func (x *ExpireService) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireService.ProtoReflect.Descriptor instead.
func (*ExpireService) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{27}
}

func (x *ExpireService) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExpireService) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ExpireService) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ExpireService) GetGuardRevision() int64 {
	if x != nil {
		return x.GuardRevision
	}
	return 0
}

type Snapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastIncludedIndex int64                  `protobuf:"varint,1,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	Term              int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Kvs               []*KVRecord            `protobuf:"bytes,3,rep,name=kvs,proto3" json:"kvs,omitempty"`
	Instances         []*InstanceRecord      `protobuf:"bytes,4,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{28}
}

func (x *Snapshot) GetLastIncludedIndex() int64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *Snapshot) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Snapshot) GetKvs() []*KVRecord {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *Snapshot) GetInstances() []*InstanceRecord {
	if x != nil {
		return x.Instances
	}
	return nil
}

type KVRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            *KeyValue              `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVRecord) Reset() {
	*x = KVRecord{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVRecord) ProtoMessage() {}

func (x *KVRecord) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVRecord.ProtoReflect.Descriptor instead.
func (*KVRecord) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{29}
}

func (x *KVRecord) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

type InstanceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceRecord) Reset() {
	*x = InstanceRecord{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceRecord) ProtoMessage() {}

func (x *InstanceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceRecord.ProtoReflect.Descriptor instead.
func (*InstanceRecord) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{30}
}

func (x *InstanceRecord) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type AppendEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AppendEntriesRequest_Snapshot
	//	*AppendEntriesRequest_Entry
	Payload       isAppendEntriesRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{31}
}

func (x *AppendEntriesRequest) GetPayload() isAppendEntriesRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AppendEntriesRequest) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Payload.(*AppendEntriesRequest_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *AppendEntriesRequest) GetEntry() *LogEntry {
	if x != nil {
		if x, ok := x.Payload.(*AppendEntriesRequest_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

type isAppendEntriesRequest_Payload interface {
	isAppendEntriesRequest_Payload()
}

type AppendEntriesRequest_Snapshot struct {
	// 流建立后的第一条消息：leader 全量快照（follower 落后太多或为空时）
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type AppendEntriesRequest_Entry struct {
	Entry *LogEntry `protobuf:"bytes,2,opt,name=entry,proto3,oneof"`
}

func (*AppendEntriesRequest_Snapshot) isAppendEntriesRequest_Payload() {}

func (*AppendEntriesRequest_Entry) isAppendEntriesRequest_Payload() {}

type AppendEntriesResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	FollowerId int32                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	// 本 follower 已持久化（内存中已追加）并应用到的最大 index
	AckIndex      int64 `protobuf:"varint,2,opt,name=ack_index,json=ackIndex,proto3" json:"ack_index,omitempty"`
	Success       bool  `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_distconf_v1_distconf_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distconf_v1_distconf_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_distconf_v1_distconf_proto_rawDescGZIP(), []int{32}
}

func (x *AppendEntriesResponse) GetFollowerId() int32 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *AppendEntriesResponse) GetAckIndex() int64 {
	if x != nil {
		return x.AckIndex
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_distconf_v1_distconf_proto protoreflect.FileDescriptor

const file_distconf_v1_distconf_proto_rawDesc = "" +
	"\n" +
	"\x1adistconf/v1/distconf.proto\x12\vdistconf.v1\"\xbf\x01\n" +
	"\bKeyValue\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x03R\brevision\x12\x15\n" +
	"\x06ttl_ms\x18\x06 \x01(\x03R\x05ttlMs\x12 \n" +
	"\fexpire_at_ms\x18\a \x01(\x03R\n" +
	"expireAtMs\"<\n" +
	"\n" +
	"GetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x92\x01\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12%\n" +
	"\x02kv\x18\x02 \x01(\v2\x15.distconf.v1.KeyValueR\x02kv\x12)\n" +
	"\x10applied_revision\x18\x03 \x01(\x03R\x0fappliedRevision\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\x05R\bleaderId\"\x94\x01\n" +
	"\n" +
	"PutRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x15\n" +
	"\x06ttl_ms\x18\x04 \x01(\x03R\x05ttlMs\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x03R\x0fexpectedVersion\"Q\n" +
	"\vPutResponse\x12%\n" +
	"\x02kv\x18\x01 \x01(\v2\x15.distconf.v1.KeyValueR\x02kv\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\"j\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\"_\n" +
	"\x0eDeleteResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\x05R\bleaderId\"c\n" +
	"\fWatchRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12#\n" +
	"\rfrom_revision\x18\x03 \x01(\x03R\ffromRevision\"\xec\x01\n" +
	"\n" +
	"WatchEvent\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.distconf.v1.WatchEvent.KindR\x04kind\x12%\n" +
	"\x02kv\x18\x02 \x01(\v2\x15.distconf.v1.KeyValueR\x02kv\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12)\n" +
	"\x10cluster_revision\x18\x04 \x01(\x03R\x0fclusterRevision\">\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x12\v\n" +
	"\aEXPIRED\x10\x03\"\xdb\x02\n" +
	"\bInstance\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.distconf.v1.Instance.MetadataEntryR\bmetadata\x12 \n" +
	"\flease_ttl_ms\x18\x06 \x01(\x03R\n" +
	"leaseTtlMs\x12 \n" +
	"\fexpire_at_ms\x18\a \x01(\x03R\n" +
	"expireAtMs\x12\x1a\n" +
	"\brevision\x18\b \x01(\x03R\brevision\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x02\n" +
	"\x0fRegisterRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12F\n" +
	"\bmetadata\x18\x05 \x03(\v2*.distconf.v1.RegisterRequest.MetadataEntryR\bmetadata\x12 \n" +
	"\flease_ttl_ms\x18\x06 \x01(\x03R\n" +
	"leaseTtlMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x10RegisterResponse\x121\n" +
	"\binstance\x18\x01 \x01(\v2\x15.distconf.v1.InstanceR\binstance\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\"k\n" +
	"\x10HeartbeatRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\"c\n" +
	"\x11HeartbeatResponse\x121\n" +
	"\binstance\x18\x01 \x01(\v2\x15.distconf.v1.InstanceR\binstance\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\"_\n" +
	"\x0fDiscoverRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x14\n" +
	"\x05watch\x18\x03 \x01(\bR\x05watch\"\xf2\x01\n" +
	"\x10DiscoverResponse\x123\n" +
	"\tinstances\x18\x01 \x03(\v2\x15.distconf.v1.InstanceR\tinstances\x12 \n" +
	"\vincremental\x18\x02 \x01(\bR\vincremental\x12+\n" +
	"\x05added\x18\x03 \x03(\v2\x15.distconf.v1.InstanceR\x05added\x12/\n" +
	"\aremoved\x18\x04 \x03(\v2\x15.distconf.v1.InstanceR\aremoved\x12)\n" +
	"\x10applied_revision\x18\x05 \x01(\x03R\x0fappliedRevision\"\r\n" +
	"\vInfoRequest\"\xe4\x01\n" +
	"\fInfoResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1b\n" +
	"\tis_leader\x18\x02 \x01(\bR\bisLeader\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\x05R\bleaderId\x12-\n" +
	"\x12committed_revision\x18\x04 \x01(\x03R\x11committedRevision\x12)\n" +
	"\x10applied_revision\x18\x05 \x01(\x03R\x0fappliedRevision\x12'\n" +
	"\x05nodes\x18\x06 \x03(\v2\x11.distconf.v1.NodeR\x05nodes\"0\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x8c\x03\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12&\n" +
	"\x03put\x18\x03 \x01(\v2\x12.distconf.v1.PutOpH\x00R\x03put\x12/\n" +
	"\x06delete\x18\x04 \x01(\v2\x15.distconf.v1.DeleteOpH\x00R\x06delete\x125\n" +
	"\bregister\x18\x05 \x01(\v2\x17.distconf.v1.RegisterOpH\x00R\bregister\x128\n" +
	"\theartbeat\x18\x06 \x01(\v2\x18.distconf.v1.HeartbeatOpH\x00R\theartbeat\x12<\n" +
	"\vexpire_keys\x18\a \x01(\v2\x19.distconf.v1.ExpireKeysOpH\x00R\n" +
	"expireKeys\x12H\n" +
	"\x0fexpire_services\x18\b \x01(\v2\x1d.distconf.v1.ExpireServicesOpH\x00R\x0eexpireServicesB\x04\n" +
	"\x02op\"\xb1\x01\n" +
	"\x05PutOp\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x15\n" +
	"\x06ttl_ms\x18\x04 \x01(\x03R\x05ttlMs\x12 \n" +
	"\fexpire_at_ms\x18\x05 \x01(\x03R\n" +
	"expireAtMs\x12)\n" +
	"\x10expected_version\x18\x06 \x01(\x03R\x0fexpectedVersion\"e\n" +
	"\bDeleteOp\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\"\xc3\x02\n" +
	"\n" +
	"RegisterOp\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.distconf.v1.RegisterOp.MetadataEntryR\bmetadata\x12 \n" +
	"\flease_ttl_ms\x18\x06 \x01(\x03R\n" +
	"leaseTtlMs\x12 \n" +
	"\fexpire_at_ms\x18\a \x01(\x03R\n" +
	"expireAtMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x01\n" +
	"\vHeartbeatOp\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12%\n" +
	"\x0eguard_revision\x18\b \x01(\x03R\rguardRevision\x12'\n" +
	"\x10new_expire_at_ms\x18\t \x01(\x03R\rnewExpireAtMsJ\x04\b\x06\x10\aJ\x04\b\a\x10\b\"<\n" +
	"\fExpireKeysOp\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.distconf.v1.ExpireKeyR\x05items\"b\n" +
	"\tExpireKey\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12%\n" +
	"\x0eguard_revision\x18\x03 \x01(\x03R\rguardRevision\"D\n" +
	"\x10ExpireServicesOp\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.distconf.v1.ExpireServiceR\x05items\"\x8f\x01\n" +
	"\rExpireService\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12%\n" +
	"\x0eguard_revision\x18\x04 \x01(\x03R\rguardRevision\"\xb2\x01\n" +
	"\bSnapshot\x12.\n" +
	"\x13last_included_index\x18\x01 \x01(\x03R\x11lastIncludedIndex\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12'\n" +
	"\x03kvs\x18\x03 \x03(\v2\x15.distconf.v1.KVRecordR\x03kvs\x129\n" +
	"\tinstances\x18\x04 \x03(\v2\x1b.distconf.v1.InstanceRecordR\tinstances\"1\n" +
	"\bKVRecord\x12%\n" +
	"\x02kv\x18\x01 \x01(\v2\x15.distconf.v1.KeyValueR\x02kv\"C\n" +
	"\x0eInstanceRecord\x121\n" +
	"\binstance\x18\x01 \x01(\v2\x15.distconf.v1.InstanceR\binstance\"\x85\x01\n" +
	"\x14AppendEntriesRequest\x123\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x15.distconf.v1.SnapshotH\x00R\bsnapshot\x12-\n" +
	"\x05entry\x18\x02 \x01(\v2\x15.distconf.v1.LogEntryH\x00R\x05entryB\t\n" +
	"\apayload\"o\n" +
	"\x15AppendEntriesResponse\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x05R\n" +
	"followerId\x12\x1b\n" +
	"\tack_index\x18\x02 \x01(\x03R\backIndex\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\x81\x02\n" +
	"\tKVService\x128\n" +
	"\x03Get\x12\x17.distconf.v1.GetRequest\x1a\x18.distconf.v1.GetResponse\x128\n" +
	"\x03Put\x12\x17.distconf.v1.PutRequest\x1a\x18.distconf.v1.PutResponse\x12A\n" +
	"\x06Delete\x12\x1a.distconf.v1.DeleteRequest\x1a\x1b.distconf.v1.DeleteResponse\x12=\n" +
	"\x05Watch\x12\x19.distconf.v1.WatchRequest\x1a\x17.distconf.v1.WatchEvent0\x012\xc0\x02\n" +
	"\x0fRegistryService\x12G\n" +
	"\bRegister\x12\x1c.distconf.v1.RegisterRequest\x1a\x1d.distconf.v1.RegisterResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.distconf.v1.HeartbeatRequest\x1a\x1e.distconf.v1.HeartbeatResponse\x12G\n" +
	"\bDiscover\x12\x1c.distconf.v1.DiscoverRequest\x1a\x1d.distconf.v1.DiscoverResponse\x12O\n" +
	"\x0eWatchInstances\x12\x1c.distconf.v1.DiscoverRequest\x1a\x1d.distconf.v1.DiscoverResponse0\x012M\n" +
	"\x0eClusterService\x12;\n" +
	"\x04Info\x12\x18.distconf.v1.InfoRequest\x1a\x19.distconf.v1.InfoResponse2p\n" +
	"\x12ReplicationService\x12Z\n" +
	"\rAppendEntries\x12\".distconf.v1.AppendEntriesResponse\x1a!.distconf.v1.AppendEntriesRequest(\x010\x01B8Z6github.com/example/distconf/api/distconf/v1;distconfv1b\x06proto3"

var (
	file_distconf_v1_distconf_proto_rawDescOnce sync.Once
	file_distconf_v1_distconf_proto_rawDescData []byte
)

func file_distconf_v1_distconf_proto_rawDescGZIP() []byte {
	file_distconf_v1_distconf_proto_rawDescOnce.Do(func() {
		file_distconf_v1_distconf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distconf_v1_distconf_proto_rawDesc), len(file_distconf_v1_distconf_proto_rawDesc)))
	})
	return file_distconf_v1_distconf_proto_rawDescData
}

var file_distconf_v1_distconf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_distconf_v1_distconf_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_distconf_v1_distconf_proto_goTypes = []any{
	(WatchEvent_Kind)(0),          // 0: distconf.v1.WatchEvent.Kind
	(*KeyValue)(nil),              // 1: distconf.v1.KeyValue
	(*GetRequest)(nil),            // 2: distconf.v1.GetRequest
	(*GetResponse)(nil),           // 3: distconf.v1.GetResponse
	(*PutRequest)(nil),            // 4: distconf.v1.PutRequest
	(*PutResponse)(nil),           // 5: distconf.v1.PutResponse
	(*DeleteRequest)(nil),         // 6: distconf.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 7: distconf.v1.DeleteResponse
	(*WatchRequest)(nil),          // 8: distconf.v1.WatchRequest
	(*WatchEvent)(nil),            // 9: distconf.v1.WatchEvent
	(*Instance)(nil),              // 10: distconf.v1.Instance
	(*RegisterRequest)(nil),       // 11: distconf.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 12: distconf.v1.RegisterResponse
	(*HeartbeatRequest)(nil),      // 13: distconf.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 14: distconf.v1.HeartbeatResponse
	(*DiscoverRequest)(nil),       // 15: distconf.v1.DiscoverRequest
	(*DiscoverResponse)(nil),      // 16: distconf.v1.DiscoverResponse
	(*InfoRequest)(nil),           // 17: distconf.v1.InfoRequest
	(*InfoResponse)(nil),          // 18: distconf.v1.InfoResponse
	(*Node)(nil),                  // 19: distconf.v1.Node
	(*LogEntry)(nil),              // 20: distconf.v1.LogEntry
	(*PutOp)(nil),                 // 21: distconf.v1.PutOp
	(*DeleteOp)(nil),              // 22: distconf.v1.DeleteOp
	(*RegisterOp)(nil),            // 23: distconf.v1.RegisterOp
	(*HeartbeatOp)(nil),           // 24: distconf.v1.HeartbeatOp
	(*ExpireKeysOp)(nil),          // 25: distconf.v1.ExpireKeysOp
	(*ExpireKey)(nil),             // 26: distconf.v1.ExpireKey
	(*ExpireServicesOp)(nil),      // 27: distconf.v1.ExpireServicesOp
	(*ExpireService)(nil),         // 28: distconf.v1.ExpireService
	(*Snapshot)(nil),              // 29: distconf.v1.Snapshot
	(*KVRecord)(nil),              // 30: distconf.v1.KVRecord
	(*InstanceRecord)(nil),        // 31: distconf.v1.InstanceRecord
	(*AppendEntriesRequest)(nil),  // 32: distconf.v1.AppendEntriesRequest
	(*AppendEntriesResponse)(nil), // 33: distconf.v1.AppendEntriesResponse
	nil,                           // 34: distconf.v1.Instance.MetadataEntry
	nil,                           // 35: distconf.v1.RegisterRequest.MetadataEntry
	nil,                           // 36: distconf.v1.RegisterOp.MetadataEntry
}
var file_distconf_v1_distconf_proto_depIdxs = []int32{
	1,  // 0: distconf.v1.GetResponse.kv:type_name -> distconf.v1.KeyValue
	1,  // 1: distconf.v1.PutResponse.kv:type_name -> distconf.v1.KeyValue
	0,  // 2: distconf.v1.WatchEvent.kind:type_name -> distconf.v1.WatchEvent.Kind
	1,  // 3: distconf.v1.WatchEvent.kv:type_name -> distconf.v1.KeyValue
	34, // 4: distconf.v1.Instance.metadata:type_name -> distconf.v1.Instance.MetadataEntry
	35, // 5: distconf.v1.RegisterRequest.metadata:type_name -> distconf.v1.RegisterRequest.MetadataEntry
	10, // 6: distconf.v1.RegisterResponse.instance:type_name -> distconf.v1.Instance
	10, // 7: distconf.v1.HeartbeatResponse.instance:type_name -> distconf.v1.Instance
	10, // 8: distconf.v1.DiscoverResponse.instances:type_name -> distconf.v1.Instance
	10, // 9: distconf.v1.DiscoverResponse.added:type_name -> distconf.v1.Instance
	10, // 10: distconf.v1.DiscoverResponse.removed:type_name -> distconf.v1.Instance
	19, // 11: distconf.v1.InfoResponse.nodes:type_name -> distconf.v1.Node
	21, // 12: distconf.v1.LogEntry.put:type_name -> distconf.v1.PutOp
	22, // 13: distconf.v1.LogEntry.delete:type_name -> distconf.v1.DeleteOp
	23, // 14: distconf.v1.LogEntry.register:type_name -> distconf.v1.RegisterOp
	24, // 15: distconf.v1.LogEntry.heartbeat:type_name -> distconf.v1.HeartbeatOp
	25, // 16: distconf.v1.LogEntry.expire_keys:type_name -> distconf.v1.ExpireKeysOp
	27, // 17: distconf.v1.LogEntry.expire_services:type_name -> distconf.v1.ExpireServicesOp
	36, // 18: distconf.v1.RegisterOp.metadata:type_name -> distconf.v1.RegisterOp.MetadataEntry
	26, // 19: distconf.v1.ExpireKeysOp.items:type_name -> distconf.v1.ExpireKey
	28, // 20: distconf.v1.ExpireServicesOp.items:type_name -> distconf.v1.ExpireService
	30, // 21: distconf.v1.Snapshot.kvs:type_name -> distconf.v1.KVRecord
	31, // 22: distconf.v1.Snapshot.instances:type_name -> distconf.v1.InstanceRecord
	1,  // 23: distconf.v1.KVRecord.kv:type_name -> distconf.v1.KeyValue
	10, // 24: distconf.v1.InstanceRecord.instance:type_name -> distconf.v1.Instance
	29, // 25: distconf.v1.AppendEntriesRequest.snapshot:type_name -> distconf.v1.Snapshot
	20, // 26: distconf.v1.AppendEntriesRequest.entry:type_name -> distconf.v1.LogEntry
	2,  // 27: distconf.v1.KVService.Get:input_type -> distconf.v1.GetRequest
	4,  // 28: distconf.v1.KVService.Put:input_type -> distconf.v1.PutRequest
	6,  // 29: distconf.v1.KVService.Delete:input_type -> distconf.v1.DeleteRequest
	8,  // 30: distconf.v1.KVService.Watch:input_type -> distconf.v1.WatchRequest
	11, // 31: distconf.v1.RegistryService.Register:input_type -> distconf.v1.RegisterRequest
	13, // 32: distconf.v1.RegistryService.Heartbeat:input_type -> distconf.v1.HeartbeatRequest
	15, // 33: distconf.v1.RegistryService.Discover:input_type -> distconf.v1.DiscoverRequest
	15, // 34: distconf.v1.RegistryService.WatchInstances:input_type -> distconf.v1.DiscoverRequest
	17, // 35: distconf.v1.ClusterService.Info:input_type -> distconf.v1.InfoRequest
	33, // 36: distconf.v1.ReplicationService.AppendEntries:input_type -> distconf.v1.AppendEntriesResponse
	3,  // 37: distconf.v1.KVService.Get:output_type -> distconf.v1.GetResponse
	5,  // 38: distconf.v1.KVService.Put:output_type -> distconf.v1.PutResponse
	7,  // 39: distconf.v1.KVService.Delete:output_type -> distconf.v1.DeleteResponse
	9,  // 40: distconf.v1.KVService.Watch:output_type -> distconf.v1.WatchEvent
	12, // 41: distconf.v1.RegistryService.Register:output_type -> distconf.v1.RegisterResponse
	14, // 42: distconf.v1.RegistryService.Heartbeat:output_type -> distconf.v1.HeartbeatResponse
	16, // 43: distconf.v1.RegistryService.Discover:output_type -> distconf.v1.DiscoverResponse
	16, // 44: distconf.v1.RegistryService.WatchInstances:output_type -> distconf.v1.DiscoverResponse
	18, // 45: distconf.v1.ClusterService.Info:output_type -> distconf.v1.InfoResponse
	32, // 46: distconf.v1.ReplicationService.AppendEntries:output_type -> distconf.v1.AppendEntriesRequest
	37, // [37:47] is the sub-list for method output_type
	27, // [27:37] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_distconf_v1_distconf_proto_init() }
func file_distconf_v1_distconf_proto_init() {
	if File_distconf_v1_distconf_proto != nil {
		return
	}
	file_distconf_v1_distconf_proto_msgTypes[19].OneofWrappers = []any{
		(*LogEntry_Put)(nil),
		(*LogEntry_Delete)(nil),
		(*LogEntry_Register)(nil),
		(*LogEntry_Heartbeat)(nil),
		(*LogEntry_ExpireKeys)(nil),
		(*LogEntry_ExpireServices)(nil),
	}
	file_distconf_v1_distconf_proto_msgTypes[31].OneofWrappers = []any{
		(*AppendEntriesRequest_Snapshot)(nil),
		(*AppendEntriesRequest_Entry)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distconf_v1_distconf_proto_rawDesc), len(file_distconf_v1_distconf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_distconf_v1_distconf_proto_goTypes,
		DependencyIndexes: file_distconf_v1_distconf_proto_depIdxs,
		EnumInfos:         file_distconf_v1_distconf_proto_enumTypes,
		MessageInfos:      file_distconf_v1_distconf_proto_msgTypes,
	}.Build()
	File_distconf_v1_distconf_proto = out.File
	file_distconf_v1_distconf_proto_goTypes = nil
	file_distconf_v1_distconf_proto_depIdxs = nil
}
